{"name": "test_case_5", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_case_5():\n        \"\"\"没标记severity的用例默认为normal\"\"\"\n        print(\"test case 555555\")\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_01.py:43: AssertionError"}, "description": "没标记severity的用例默认为normal", "attachments": [{"name": "stdout", "source": "25161138-3b45-4246-9997-ef337f0c3152-attachment.txt", "type": "text/plain"}], "start": 1600681046172, "stop": 1600681046173, "uuid": "c71a5223-1eaf-42b1-a97b-924f76bf6998", "historyId": "39498477ebdf4ebe5c48dd09c15c8b18", "testCaseId": "42fcfa327c74c7e995c3fb28c8cbc4ba", "fullName": "test_01#test_case_5", "labels": [{"name": "suite", "value": "test_01"}, {"name": "host", "value": "PC-20160818TLFG"}, {"name": "thread", "value": "14308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}